image: .NET Core SDK 5.0.300

environment:
  matrix:
    - BUILD_TYPE: "Debug"
    - BUILD_TYPE: "Release"

build_script:
  - dotnet restore
  - dotnet build --configuration %BUILD_TYPE%
  - dotnet publish --configuration %BUILD_TYPE%
