version: '3.0'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: MicroCRMDB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: ./src/backend/MicroCRM/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      DB_CONNECTION_STRING: Server=db;Port=5432;User ID=postgres;Password=root;Database=MicroCRMDB;
    ports:
      - '5000:80'

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    depends_on:
      - db
      - backend
    ports:
      - '4200:4200'
